# Generated by Django 4.1.7 on 2023-03-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_dicription_performance_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
