# Generated by Django 4.1.7 on 2023-03-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_test_performance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/'),
        ),
    ]
